AWSTemplateFormatVersion: '2010-09-09'
Description: Security things like ACL Security Groups IAM
Parameters: {}
Resources:
  EC2BootstrapRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
  EC2BootstrapPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ec2_bootstrap_policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:DescribeInstances
          - ec2:DescribeTags
          - ec2:CreateTags
          Resource:
          - '*'
      Roles:
      - !Ref 'EC2BootstrapRole'
Outputs: {}
